name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Restore nuget
        run: nuget restore
      - name: Android
        run: msbuild /t:restore /p:Configuration=Debug ./Swimclub.Mobile/Swimclub.Mobile.Android/Swimclub.Droid.csproj
  ASPNET:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Restore nuget
        run: nuget restore
      - name: ASPNET
        run: msbuild /t:restore /p:Configuration=Debug ./Swimclub.REST/Swimclub.REST.csproj
  UNITTESTING:
    runs-on: macos-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Restore nuget
        run: nuget restore
      - name: UNITTEST
        run: dotnet test /Swimclub.MSTEST/Swimclub.MSTest.csproj
        
